a:5:{i:0;s:100:"SQLSTATE[HY000] [2002] No connection could be made because the target machine actively refused it.
";i:1;s:1667:"#0 E:\WORKSPACE\xampp\htdocs\magento\lib\Zend\Db\Adapter\Pdo\Mysql.php(109): Zend_Db_Adapter_Pdo_Abstract->_connect()
#1 E:\WORKSPACE\xampp\htdocs\magento\lib\Varien\Db\Adapter\Pdo\Mysql.php(320): Zend_Db_Adapter_Pdo_Mysql->_connect()
#2 E:\WORKSPACE\xampp\htdocs\magento\lib\Zend\Db\Adapter\Abstract.php(460): Varien_Db_Adapter_Pdo_Mysql->_connect()
#3 E:\WORKSPACE\xampp\htdocs\magento\lib\Zend\Db\Adapter\Pdo\Abstract.php(238): Zend_Db_Adapter_Abstract->query('SET NAMES utf8', Array)
#4 E:\WORKSPACE\xampp\htdocs\magento\lib\Varien\Db\Adapter\Pdo\Mysql.php(428): Zend_Db_Adapter_Pdo_Abstract->query('SET NAMES utf8', Array)
#5 E:\WORKSPACE\xampp\htdocs\magento\app\code\core\Mage\Core\Model\Resource.php(169): Varien_Db_Adapter_Pdo_Mysql->query('SET NAMES utf8')
#6 E:\WORKSPACE\xampp\htdocs\magento\app\code\core\Mage\Core\Model\Resource.php(110): Mage_Core_Model_Resource->_newConnection('pdo_mysql', Object(Mage_Core_Model_Config_Element))
#7 E:\WORKSPACE\xampp\htdocs\magento\app\code\core\Mage\Core\Model\Resource\Setup.php(141): Mage_Core_Model_Resource->getConnection('core_setup')
#8 E:\WORKSPACE\xampp\htdocs\magento\app\code\core\Mage\Core\Model\Resource\Setup.php(234): Mage_Core_Model_Resource_Setup->__construct('core_setup')
#9 E:\WORKSPACE\xampp\htdocs\magento\app\code\core\Mage\Core\Model\App.php(417): Mage_Core_Model_Resource_Setup::applyAllUpdates()
#10 E:\WORKSPACE\xampp\htdocs\magento\app\code\core\Mage\Core\Model\App.php(343): Mage_Core_Model_App->_initModules()
#11 E:\WORKSPACE\xampp\htdocs\magento\app\Mage.php(684): Mage_Core_Model_App->run(Array)
#12 E:\WORKSPACE\xampp\htdocs\magento\index.php(87): Mage::run('', 'store')
#13 {main}";s:3:"url";s:1:"/";s:11:"script_name";s:10:"/index.php";s:4:"skin";s:7:"default";}